### ISSUE TITLE
[HELP] tproxy make network failed

### ISSUE THREAD

**Issue by spencercjh** [chaos-mesh/chaos-tproxy#67]
Here is my cfg file.

```yaml
proxy_ports: [ 8000 ]
rules: # option rule vec
  - target: Request # Request or Response.
    # Stand for target packet to select & take actions.
    # If target is Response & selecting request info such as method or path ,
    # proxy will select request and take actions on Response.
    selector:
      path: /test # option Match path of `Uri` with wildcard matches. Using [wildcard matches](https://www.wikiwand.com/en/Matching_wildcards).
      #    abc://username:password@example.com:123/path/data?key=value&key2=value2#fragid1
      #                                           |--------|
      #                                               |
      #                                             path
      method: GET # option string
      port: 8000
    actions:
      delay: 2s # option Duration
```

There is a hello-world python server running on 8000 port.

![image](https://github.com/user-attachments/assets/bd26244a-c485-40f3-979e-a9803bd00863)

Why is my ssh connection to this machine **affected** when I start the chaos-tproxy? I can't ssh to the instance until I reboot.

![23acd1fc1c6ef4be9465c48974041076](https://github.com/user-attachments/assets/b3194972-bc95-486c-993f-19de8995ae3e)

I never saw logs after `Uds listener listening on xxx` because the ssh connection was closed... 

Also I can't access the http server on port 8000 anymore.
